### ISSUE TITLE
diagrams are not generated

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#619]

**Comment by ahmad88me** [comment]
Issue was related to java
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: org/apache/jena/riot/RiotException
	at es.upm.oeg.ar2dtool.Main.main(Main.java:62)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.jena.riot.RiotException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```
This could be related to the newer version of java
